--delete type_promo

--select * from type_promo

-- 00 Bloque
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(0, 'Bloque', '', '', '000')

-- 01 Artículo Descuento en Bono o Monedero
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(1, 'Artículo Descuento en Bono o Monedero', '&nbsp;&nbsp;HMMSe declara en promoción a un conjunto de artículos con cantidades específicas, y se le  aplica un descuento a todos los artículos de este conjunto que se encuentren contenidos en el ticket, en cantidades múltiplo de las cantidades específicas  antes mencionadas.<br/>&nbsp;&nbsp;El descuento aplicado puede ser de 2 tipos: (a) <b><i>Descuento porcentual</i></b>, en donde se calcula un porcentaje de  descuento sobre el precio de cada artículo beneficiado, o (b) <b><i>Descuento de monto fijo</i></b> por intervalo de dinero, en donde se descuenta una X  cantidad de dinero por cada Y unidades de dinero que sumen los artículos beneficiados.<br/>&nbsp;&nbsp;El beneficio otorgado por la promoción se entrega en  un <b><i>bono</i></b> que contiene el monto de descuento calculado, o puede ser entregado como puntos en el <b><i>monedero</i></b> electrónico.', '',  '001')

-- 02 Artículo Descuento en Ticket
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(2, 'Artículo Descuento en Ticket', '&nbsp;&nbsp;Se declara en promoción a un conjunto de artículos con cantidades específicas, y se le aplica un  descuento a todos los artículos de este conjunto que se encuentren contenidos en el ticket, en cantidades múltiplo de las cantidades específicas antes  mencionadas.<br/>&nbsp;&nbsp;El descuento aplicado puede ser de 2 tipos: (a) <b><i>Descuento porcentual</i></b>, en donde se calcula un porcentaje de  descuento sobre el precio de cada artículo beneficiado, o (b) <b><i>Descuento de monto fijo</i></b> por intervalo de dinero, en donde se descuenta una X  cantidad de dinero por cada Y unidades de dinero que sumen los artículos beneficiados.<br/>&nbsp;&nbsp;El descuento calculado por la promoción se aplica al  ticket. Según configuración, dicho descuento puede ser aplicado sobre un único artículo de descarga, o sobre cada artículo beneficiado.', '', '002')

-- 03 Grupo Completo Descuento en Bono o Monedero
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(3, 'Grupo Completo Descuento en Bono o Monedero', '&nbsp;&nbsp;Se declara en promoción a un grupo de artículos con cantidades específicas, y se le  aplica un descuento a todos los grupos que se encuentren íntegramente contenidos en el ticket, hasta un máximo de grupos previamente  establecido.<br/>&nbsp;&nbsp;El descuento aplicado puede ser de 2 tipos: (a) <b><i>Descuento porcentual</i></b>, en donde se calcula un porcentaje de  descuento sobre el precio de cada artículo beneficiado, o (b) <b><i>Descuento de monto fijo</i></b> por intervalo de dinero, en donde se descuenta una X  cantidad de dinero por cada Y unidades de dinero que sumen los artículos beneficiados.<br/>&nbsp;&nbsp;El beneficio otorgado por la promoción se entrega en  un <b><i>bono</i></b> que contiene el monto de descuento calculado, o puede ser entregado como puntos en el <b><i>monedero</i></b> electrónico.', '', '003')

-- 04 Grupo Completo Descuento en Ticket
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(4, 'Grupo Completo Descuento en Ticket', '&nbsp;&nbsp;Se declara en promoción a un <i>grupo</i> de artículos con <i>cantidades específicas</i>, y  se le aplica un descuento a todos los grupos que se encuentren <i>íntegramente</i> contenidos en el ticket, hasta un máximo de grupos previamente  establecido.<br/>&nbsp;&nbsp;El descuento aplicado puede ser de 2 tipos: (a) <b><i>Descuento porcentual</i></b>, en donde se calcula un porcentaje de  descuento sobre el precio de cada artículo beneficiado, o (b) <b><i>Descuento de monto fijo</i></b> por intervalo de dinero, en donde se descuenta una X  cantidad de dinero por cada Y unidades de dinero que sumen los artículos beneficiados. El descuento calculado por la promoción se aplica al ticket. Según  configuración, dicho descuento puede ser aplicado sobre un único artículo de descarga, o sobre cada artículo beneficiado.', '', '004')


-- 05 Importe Total Descuento en Bono o Monedero
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(5, 'Importe Total Descuento en Bono o Monedero', '&nbsp;&nbsp;Esta promoción calcula un descuento sobre todos los artículos contenidos en el  ticket, con excepción de aquellos artículos declarados como no promocionables. El monto de dicho descuento no debe superar el <b><i>Límite máximo de  dinero</i></b> establecido.<br/>&nbsp;&nbsp;El descuento aplicado puede ser de 2 tipos: (a) <b><i>Descuento porcentual</i></b>, en donde se calcula un  porcentaje de descuento sobre el precio de cada artículo beneficiado, o (b) <b><i>Descuento de monto fijo</i></b> por intervalo de dinero, en donde se  descuenta una X cantidad de dinero por cada Y unidades de dinero que sumen los artículos beneficiados.<br/>&nbsp;&nbsp;El cálculo del descuento puede ser  realizado sobre el importe original de los artículos, o sobre el valor resultante de haber aplicado sobre ellos otras promociones (<b><i>Aplica sobre  beneficios anteriores</i></b>).<br/>&nbsp;&nbsp;El beneficio otorgado por la promoción se entrega en un <b><i>bono</i></b> que contiene el monto de descuento  calculado, o puede ser entregado como puntos en el <b><i>monedero</i></b> electrónico.', '', '005')

-- 06 Importe Total Descuento en Ticket
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(6, 'Importe Total Descuento en Ticket', '&nbsp;&nbsp;Esta promoción calcula un descuento sobre todos los artículos contenidos en el ticket, con  excepción de aquellos artículos declarados como no promocionables. El monto de dicho descuento no debe superar el <b><i>Límite máximo de dinero</i></b>  establecido.<br/>&nbsp;&nbsp;El descuento aplicado puede ser de 2 tipos: (a) <b><i>Descuento porcentual</i></b>, en donde se calcula un porcentaje de  descuento sobre el precio de cada artículo beneficiado, o (b) <b><i>Descuento de monto fijo</i></b> por intervalo de dinero, en donde se descuenta una X  cantidad de dinero por cada Y unidades de dinero que sumen los artículos beneficiados.<br/>&nbsp;&nbsp;El cálculo del descuento puede ser realizado sobre el  importe original de los artículos, o sobre el valor resultante de haber aplicado sobre ellos otras promociones (<b><i>Aplica sobre beneficios  anteriores</i></b>).<br/>&nbsp;&nbsp;El descuento calculado por la promoción se aplica al ticket, sobre un artículo de descarga previamente configurado.',  '', '006')

-- 07 Departamento Descuento en Bono o Monedero
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(7, 'Departamento Descuento en Bono o Monedero', '&nbsp;&nbsp;Se declara en promoción a un conjunto de departamentos, y se le aplica un descuento a  todos los artículos contenidos en el ticket, que pertenezcan a alguno de estos departamentos.&nbsp;&nbsp;El descuento aplicado puede ser de 2 tipos: (a)  <b><i>Descuento porcentual</i></b>, en donde se calcula un porcentaje de descuento sobre el precio de cada artículo beneficiado, o (b) <b><i>Descuento de  monto fijo</i></b> por intervalo de dinero, en donde se descuenta una X cantidad de dinero por cada Y unidades de dinero que sumen los artículos  beneficiados.<br/>&nbsp;&nbsp;El cálculo del descuento puede ser realizado sobre el importe original de los artículos, o sobre el valor resultante de haber  aplicado sobre ellos otras promociones (<b><i>Aplica sobre beneficios anteriores</i></b>).<br/>&nbsp;&nbsp;El beneficio otorgado por la promoción se entrega  en un <b><i>bono</i></b> que contiene el monto de descuento calculado, o puede ser entregado como puntos en el <b><i>monedero</i></b> electrónico.', '',  '007')

-- 08 Departamento Descuento en Ticket
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(8, 'Departamento Descuento en Ticket', '&nbsp;&nbsp;Se declara en promoción a un conjunto de departamentos, y se le aplica un descuento a todos los  artículos contenidos en el ticket, que pertenezcan a alguno de estos departamentos.&nbsp;&nbsp;El descuento aplicado puede ser de 2 tipos: (a)  <b><i>Descuento porcentual</i></b>, en donde se calcula un porcentaje de descuento sobre el precio de cada artículo beneficiado, o (b) <b><i>Descuento de  monto fijo</i></b> por intervalo de dinero, en donde se descuenta una X cantidad de dinero por cada Y unidades de dinero que sumen los artículos  beneficiados.<br/>&nbsp;&nbsp;El cálculo del descuento puede ser realizado sobre el importe original de los artículos, o sobre el valor resultante de haber  aplicado sobre ellos otras promociones (<b><i>Aplica sobre beneficios anteriores</i></b>).<br/>&nbsp;&nbsp;El descuento calculado por la promoción se aplica  al ticket, sobre un artículo de descarga previamente configurado.', '', '008')

-- 09 Artículo Agregar Artículo en Bono o Monedero
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(9, 'Artículo Agregar Artículo en Bono o Monedero', '&nbsp;&nbsp;Se declara en promoción a un artículo <b><i>A</i></b>. Luego, por cada  <b><i>m</i></b> artículos del tipo <b><i>A</i></b> que hayan sido comprados, la promoción regala <b><i>n</i></b> de ellos. Notemos que la cantidad de  artículos que se regalan debe ser siempre menor a la cantidad de artículos que se compran (n < m).<br/>&nbsp;&nbsp;Supongamos que no se desea regalar el  importe total de los artículos beneficiados, sino solamente una parte de ellos. Para poder lograr este objetivo se debe configurar la opción <i>Se bonifica  sólo un porcentaje del artículo</i>, indicando en el campo <i>Porcentaje de descuento</i>, el porcentaje de descuento que se desee  aplicar.<br/>&nbsp;&nbsp;El beneficio otorgado por la promoción se entrega en un <b><i>bono</i></b> que contiene el monto de descuento calculado, o puede ser  entregado como puntos en el <i><b>monedero</b></i> electrónico.', '', '009')

-- 10 Artículo Agregar Artículo en Ticket
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(10, 'Artículo Agregar Artículo en Ticket', '&nbsp;&nbsp;Se declara en promoción a un artículo <b><i>A</b></i>. Luego, por cada <b><i>m</i></b> artículos del tipo <b><i>A</i></b>  que hayan sido comprados, la promoción regala <b><i>n</i></b> de ellos. Notemos que la cantidad de artículos que se regalan debe ser siempre menor a la  cantidad de artículos que se compran (n < m).<br/>&nbsp;&nbsp;Supongamos que no se desea regalar el importe total de los artículos beneficiados, sino  solamente una parte de ellos. Para poder lograr este objetivo se debe configurar la opción <i>Se bonifica sólo un porcentaje del artículo</i>, indicando en  el campo <i>Porcentaje de descuento</i>, el porcentaje de descuento que se desee aplicar.<br/>&nbsp;&nbsp;El descuento calculado por la promoción se aplica  al ticket. Según configuración, dicho descuento puede ser aplicado sobre un artículo de descarga ficticio, o sobre el artículo beneficiado.', '', '010')

-- 11 Grupo Agregar Artículo en Bono o Monedero
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(11, 'Grupo Agregar Artículo en Bono o Monedero',  '&nbsp;&nbsp;Se declara en promoción a un <i>grupo</i> de artículos con <i>cantidades específicas</i>. Luego, se cuentan todos los grupos  <i>completos</i> que hayan sido comprados y, por cada <b><i>m</i></b> artículos pertenecientes a estos grupos, se regalan <b><i>n</i></b> (elegidos al  azar).<br/>&nbsp;&nbsp;Supongamos que no se desea regalar el importe total de los artículos beneficiados, sino solamente una parte de ellos. Para poder  lograr este objetivo se debe configurar la opción <i>Se bonifica sólo un porcentaje del artículo</i>, indicando en el campo <i>Porcentaje de descuento</i>,  el porcentaje de descuento que se desee aplicar.<br/>&nbsp;&nbsp;El beneficio otorgado por la promoción se entrega en un <b><i>bono</i></b> que contiene el  monto de descuento calculado, o puede ser entregado como puntos en el <b><i>monedero</i></b> electrónico.', '', '011')

-- 12 Grupo Agregar Artículo en Ticket
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(12, 'Grupo Agregar Artículo en Ticket', '&nbsp;&nbsp;Se declara en promoción a un <i>grupo</i> de artículos con <i>cantidades específicas</i>. Luego, se cuentan todos los grupos  <i>completos</i> que hayan sido comprados y, por cada <b><i>m</i></b> artículos pertenecientes a estos grupos, se regalan <b><i>n</i></b> (elegidos al  azar).<br/>&nbsp;&nbsp;Supongamos que no se desea regalar el importe total de los artículos beneficiados, sino solamente una parte de ellos. Para poder  lograr este objetivo se debe configurar la opción <i>Se bonifica sólo un porcentaje del artículo</i>, indicando en el campo <i>Porcentaje de descuento</i>,  el porcentaje de descuento que se desee aplicar.<br/>&nbsp;&nbsp;El descuento calculado por la promoción se aplica al ticket. Según configuración, dicho  descuento puede ser aplicado sobre un único artículo de descarga, o sobre cada artículo beneficiado.', '', '012')

-- 15 Grupo Descuento Caros Baratos en Bono o Monedero
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(15, 'Grupo Descuento Caros Baratos en Bono o Monedero', '&nbsp;&nbsp;Se declara en promoción a un conjunto de artículos con <i>cantidades específicas</i>. Luego, por cada <b><i>m</i></b> de  estos artículos que hayan sido comprados, se regalan <b><i>n</i></b>. Los artículos a regalar pueden ser los más caros o los más baratos, según  configuración.<br/>&nbsp;&nbsp;Supongamos que no se desea regalar el importe total de los artículos beneficiados, sino solamente una parte de ellos. Para  poder lograr este objetivo se debe configurar la opción <i>Se bonifica sólo un porcentaje del artículo</i>, indicando en el campo <i>Porcentaje de  descuento</i>, el porcentaje de descuento que se desee aplicar.<br/>&nbsp;&nbsp;El beneficio otorgado por la promoción se entrega en un <b><i>bono</i></b>  que contiene el monto de descuento calculado, o puede ser entregado como puntos en el <b><i>monedero</i></b> electrónico.', '', '015')

-- 16 Grupo Descuento Caros Baratos en Ticket
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(16, 'Grupo Descuento Caros Baratos en Ticket', '&nbsp;&nbsp;Se declara en promoción a un conjunto de artículos con <i>cantidades específicas</i>. Luego, por cada <b><i>m</i></b> de  estos artículos que hayan sido comprados, se regalan <b><i>n</i></b>. Los artículos a regalar pueden ser los más caros o los más baratos, según  configuración.<br/>&nbsp;&nbsp;Supongamos que no se desea regalar el importe total de los artículos beneficiados, sino solamente una parte de ellos. Para  poder lograr este objetivo se debe configurar la opción <i>Se bonifica sólo un porcentaje del artículo</i>, indicando en el campo <i>Porcentaje de  descuento</i>, el porcentaje de descuento que se desee aplicar.<br/>&nbsp;&nbsp;El descuento calculado por la promoción se aplica al ticket. Según  configuración, dicho descuento puede ser aplicado sobre un único artículo de descarga, o sobre cada artículo beneficiado.', '', '016')

-- 17 Artículo Cupón en Bono
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(17, 'Artículo Cupón en Bono', '&nbsp;&nbsp;Se declara en promoción a un conjunto de artículos con <i>cantidades específicas</i>. Luego, se otorgan <b><i>n</i></b>  cupones por cada <b><i>m</i></b> unidades de dinero que sumen los artículos de este conjunto que hayan sido comprados. El beneficio de la promoción se  entrega en un <b><i>bono</i></b> en donde se indica la cantidad y el tipo de cupones que deben ser entregados.', '', '017')

-- 19 Departamento Cupón en Bono
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(19, 'Departamento Cupón en Bono', '&nbsp;&nbsp;Se declara en promoción a un conjunto de departamentos. Luego, se otorgan <b><i>n</i></b> cupones por cada <b><i>m</i></b>  unidades de dinero que sumen los artículos de estos departamentos que hayan sido comprados. El beneficio de la promoción se entrega en un <b><i>bono</i></b>  en donde se indica la cantidad y el tipo de cupones que deben ser entregados.', '', '019')

-- 23 Importe Total Cupón en Bono
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(23, 'Importe Total Cupón en Bono', '&nbsp;&nbsp;Se declara en promoción al importe total del ticket. Luego, se otorgan <b><i>n</i></b> cupones por cada <b><i>m</i></b>  unidades de dinero de este importe. El beneficio de la promoción se entrega en un <b><i>bono</i></b> en donde se indica la cantidad y el tipo de cupones que  deben ser entregados.', '', '023')

-- 27 Si Pago con Medio y Submedio Descuento en Bono o Monedero
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(27, 'Si Pago con Medio y Submedio Descuento en Bono o Monedero', '&nbsp;&nbsp;Se declara en promoción a un conjunto de medios de pago. Luego, se calcula un descuento sobre el importe de dinero que haya  sido pagado con los medios de pago promocionados.<br/>&nbsp;&nbsp;El descuento calculado puede ser de 2 tipos: (a) <b><i>Descuento porcentual</i></b>, en  donde se calcula un porcentaje de descuento sobre el importe total, o (b) <b><i>Descuento de monto fijo</i></b> por intervalo de dinero, en donde se  descuenta una X cantidad de dinero por cada Y unidades de dinero del importe pagado con los medios promocionados.<br/>&nbsp;&nbsp;El beneficio otorgado por  la promoción se entrega en un <b><i>bono</i></b> que contiene el monto de descuento calculado, o puede ser entregado como puntos en el <b><i>monedero</i></b>  electrónico.', '', '027')

-- 28 Importe Total Descuento en Bono o Monedero con Medios Excluidos
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(28, 'Importe Total Descuento en Bono o Monedero con Medios Excluidos', '&nbsp;&nbsp;Esta promoción calcula un descuento sobre todos los artículos contenidos en el ticket, con excepción de aquellos artículos  declarados como no promocionables.<br/>&nbsp;&nbsp;El descuento aplicado puede ser de 2 tipos: (a) <b><i>Descuento porcentual</i></b>, en donde se calcula un  porcentaje de descuento sobre el precio de cada artículo beneficiado, o (b) <b><i>Descuento de monto fijo</i></b> por intervalo de dinero, en donde se  descuenta una X cantidad de dinero por cada Y unidades de dinero que sumen los artículos beneficiados.<br/>&nbsp;&nbsp;El beneficio otorgado por la promoción  se entrega en un <b><i>bono</i></b> que contiene el monto de descuento calculado, o puede ser entregado como puntos en el <b><i>monedero</i></b>  electrónico.', '', '028')

-- 31 Si Vuelto en Medio y Submedio Bonificar en Bono o Monedero
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(31, 'Si Vuelto en Medio y Submedio Bonificar en Bono o Monedero', '&nbsp;&nbsp;Se declara en promoción a un conjunto de medios de pago. Luego, si alguno de estos medios genera un vuelto en el monedero,  la promoción realizará una bonificación sobre el importe de este vuelto.<br/>&nbsp;&nbsp;La bonificación puede ser de 2 tipos: (a) se bonifica un porcentaje  del monto total del vuelto (<b><i>Descuento porcentual</i></b>), o (b) se bonifica una X cantidad de dinero por cada Y unidades de dinero del importe del  vuelto (<b><i>Descuento de monto fijo</i></b>).<br/>&nbsp;&nbsp;El beneficio otorgado por la promoción se entrega en un <b><i>bono</i></b> que contiene el  monto de descuento calculado, o puede ser entregado como puntos en el <b><i>monedero</i></b> electrónico.', '', '031')

-- 32 Artículo Plan Pago
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(32, 'Artículo Plan Pago', '&nbsp;&nbsp;Se declara en promoción a un conjunto <b><i>A</i></b> de artículos con <i>cantidades específicas</i> y a un conjunto  <b><i>P</i></b> de planes de pago. Luego, el importe de todos los artículos del conjunto <b><i>A</i></b> que se encuentren contenidos en el ticket, en  cantidades múltiplo de las cantidades específicas antes mencionadas, es habilitado para ser pagado con cualquiera de los planes de pago del conjunto  <b><i>P</i></b>.', '', '032')

-- 33 Departamento Plan Pago
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(33, 'Departamento Plan Pago', '&nbsp;&nbsp;Se declara en promoción a un conjunto <b><i>D</i></b> de departamentos y a un conjunto <b><i>P</i></b> de planes de pago.  Luego, el importe de todos los artículos del conjunto <b><i>D</i></b> que se encuentren contenidos en el ticket, es habilitado para ser pagado con cualquiera  de los planes de pago del conjunto <b><i>P</i></b>.', '', '033')

-- 34 Departamento Plan Pago con Artículos Excluidos
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(34, 'Departamento Plan Pago con Artículos Excluidos', '&nbsp;&nbsp;Se declara en promoción a un conjunto <b><i>D</i></b> de departamentos y a un conjunto <b><i>P</i></b> de planes de pago.  Luego, el importe de todos los artículos del conjunto <b><i>D</i></b> (con excepción de ciertos <i>artículos excluidos</i>) que se encuentren contenidos en  el ticket, es habilitado para ser pagado con cualquiera de los planes de pago del conjunto <b><i>P</i></b>.', '', '034')

-- 35 Importe Total Plan Pago con Departamentos Excluidos
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(35, 'Importe Total Plan Pago con Departamentos Excluidos', '&nbsp;&nbsp;Se declara en promoción a un conjunto <b><i>P</i></b> de planes de pago. Luego, el importe de todos los artículos del ticket  es habilitado para ser pagado con cualquiera de los planes de pago del conjunto <b><i>P</i></b>, quedando excluidos de la promoción aquellos artículos  pertenecientes a ciertos departamentos excluidos.', '', '035')

-- 36 Incondicional Plan Pago
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(36, 'Incondicional Plan Pago', '&nbsp;&nbsp;Se declara en promoción a un conjunto <b><i>P</i></b> de planes de pago. Luego, el importe de todos los artículos del ticket  es habilitado para ser pagado con cualquiera de los planes de pago del conjunto <b><i>P</i></b>.', '', '036')

-- 37 Departamento Descuento en Bono o Monedero
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(37, 'Departamento Descuento en Bono o Monedero', '&nbsp;&nbsp;Se declara en promoción a un conjunto de departamentos, y se le aplica un descuento a todos los artículos contenidos en el  ticket, que pertenezcan a alguno de estos departamentos (con excepción de <i>ciertos artículos excluidos</i>).<br/>&nbsp;&nbsp;El descuento aplicado puede  ser de 2 tipos: (a) <b><i>Descuento porcentual</i></b>, en donde se calcula un porcentaje de descuento sobre el precio de cada artículo beneficiado, o (b)  <b><i>Descuento de monto fijo</i></b> por intervalo de dinero, en donde se descuenta una X cantidad de dinero por cada Y unidades de dinero que sumen los  artículos beneficiados.<br/>&nbsp;&nbsp;El cálculo del descuento puede ser realizado sobre el importe original de los artículos, o sobre el valor resultante  de haber aplicado sobre ellos otras promociones (<b><i>Aplica sobre beneficios anteriores</i></b>).<br/>&nbsp;&nbsp;El beneficio otorgado por la promoción se  entrega en un <b><i>bono</i></b> que contiene el monto de descuento calculado, o puede ser entregado como puntos en el <b><i>monedero</i></b> electrónico.',  '', '037')

-- 38 Grupo Parcial Agregar Artículo en Ticket
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(38, 'Grupo Parcial Agregar Artículo en Ticket',  '&nbsp;&nbsp;Se declara en promoción a un conjunto <b><i>D</i></b> de artículos disparantes de la promoción y a un conjunto <b><i>B</i></b> de artículos  beneficiados por la promoción. Luego, por cada <b><i>m</i></b> artículos del conjunto <b><i>D</i></b> que hayan sido comprados, se le aplica un descuento a  un conjunto <b><i>B</i></b> completo de artículos, siempre y cuando estos últimos estén incluidos en el ticket.<br/>&nbsp;&nbsp;El descuento aplicado a los  artículos puede ser de 2 tipos: <br/>(a) <i>porcentual</i>, es decir que se aplica un porcentaje de descuento a cada artículo beneficiado, o (b) descuento  <i>por precio fijo</i>, en donde cada artículo beneficiado se entrega a un precio fijo promocional, inferior al precio real del artículo.<br/>&nbsp;&nbsp;El  descuento calculado por la promoción se aplica al ticket.', '', '038')

-- 39 Grupo Parcial Agregar Artículo en Bono o Monedero
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(39, 'Grupo Parcial Agregar Artículo en Bono o Monedero', '&nbsp;&nbsp;Se declara en promoción a un conjunto <b><i>D</i></b> de artículos disparantes de la promoción y a un conjunto  <b><i>B</i></b> de artículos beneficiados por la promoción. Luego, por cada <b><i>m</i></b> artículos del conjunto <b><i>D</i></b> que hayan sido comprados,  se le aplica un descuento a un conjunto <b><i>B</i></b> completo de artículos, siempre y cuando estos últimos estén incluidos en el  ticket.<br/>&nbsp;&nbsp;El descuento aplicado a los artículos puede ser de 2 tipos: <br/>(a) <i>porcentual</i>, es decir que se aplica un porcentaje de  descuento a cada artículo beneficiado, o (b) descuento <i>por precio fijo</i>, en donde cada artículo beneficiado se entrega a un precio fijo promocional,  inferior al precio real del artículo.<br/>&nbsp;&nbsp;El beneficio otorgado por la promoción se entrega en un <b><i>bono</i></b> que contiene el monto de  descuento calculado, o puede ser entregado como puntos en el <b><i>monedero</i></b> electrónico', '', '039')

-- 40 Departamento M x N Caros Baratos en Ticket
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(40, 'Departamento M x N Caros Baratos en Ticket', '&nbsp;&nbsp;Se declara en promoción a un conjunto <b><i>D</i></b> de departamentos y a un conjunto  <b><i>A</i></b> de artículos. Luego, por cada <b><i>m</i></b> artículos de estos conjuntos que se encuentren contenidos en el ticket, se regalan  <b><i>n</i></b>. Los artículos a regalar pueden ser los más caros o los más baratos, según configuración.<br/>&nbsp;&nbsp;Supongamos que no se desea regalar  el importe total de los artículos beneficiados, sino solamente una parte de ellos. Para poder lograr este objetivo se debe configurar la opción <i>Se  bonifica sólo un porcentaje del artículo</i>, indicando en el campo <i>Porcentaje de descuento</i>, el porcentaje de descuento que se desee  aplicar.<br/>&nbsp;&nbsp;El descuento calculado por la promoción se aplica al ticket. Según configuración, dicho descuento puede ser aplicado sobre un único  artículo de descarga, o sobre cada artículo beneficiado.', '', '040')

-- 41 M X N Artículos Iguales Múltiple en Ticket
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(41, 'M X N Artículos Iguales Múltiple en Ticket', '&nbsp;&nbsp;Se declara en promoción a distintos artículos <b><i>A</i></b>, <b><i>B</i></b>,  <b><i>C</i></b>, etc. Luego, por cada <b><i>m</i></b> artículos del tipo <b><i>A</i></b> que se encuentren incluidos en el ticket, la promoción regala  <b><i>n</i></b> de ellos. Este mismo procedimiento se repite para cada uno de los artículos que hayan sido promocionados. Notemos que la cantidad de  artículos que se regalan debe ser siempre menor a la cantidad de artículos que se compran (<b><i>n</i></b> < <b><i>m</i></b>).<br/>&nbsp;&nbsp;Supongamos que  no se desea regalar el importe total de los artículos beneficiados, sino solamente una parte de ellos. Para poder lograr este objetivo se debe configurar la  opción <i>Se bonifica sólo un porcentaje del artículo</i>, indicando en el campo <i>Porcentaje de descuento</i>, el porcentaje de descuento que se desee  aplicar.<br/>&nbsp;&nbsp;El descuento calculado por la promoción se aplica al ticket.', '', '041')

-- 42 Grupo Completo Precio Fijo en Ticket
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(42, 'Grupo Completo Precio Fijo en Ticket', '&nbsp;&nbsp;Se declara en promoción a un grupo de artículos. Luego, a cada grupo <i>completo</i> de estos  artículos que se encuentre contenido en el ticket, se le aplica un descuento fijo. Dicho descuento fijo resulta de la diferencia entre el precio real del  grupo de artículos y el precio fijo (promocional) que haya sido configurado para esa promoción.<br/>&nbsp;&nbsp;El descuento calculado por la promoción se  aplica al ticket, distribuyéndolo proporcionalmente entre todos los artículos beneficiados.', '', '042')

-- 43 Artículo por Importe Agregar Artículo en Ticket
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(43, 'Artículo por Importe Agregar Artículo en Ticket', '&nbsp;&nbsp;Se declara en promoción a un conjunto <b><i>D</i></b> de artículos disparantes de la promoción y a un conjunto  <b><i>B</i></b> de artículos beneficiados por la promoción. Luego, por cada <b><i>u</i></b> unidades de dinero que sumen los artículos del conjunto  <b><i>D</i></b> que hayan sido comprados, se le aplica un descuento a un conjunto <b><i>B</i></b> completo de artículos, siempre y cuando estos últimos estén  incluidos en el ticket.<br/>&nbsp;&nbsp;El descuento aplicado a los artículos puede ser de 2 tipos: <br/>(a) <i>porcentual</i>, es decir que se aplica un  porcentaje de descuento a cada artículo beneficiado, o (b) descuento <i>por precio fijo</i>, en donde cada artículo beneficiado se entrega a un precio fijo  promocional, inferior al precio real del artículo.<br/>&nbsp;&nbsp;El descuento calculado por la promoción se aplica al ticket.', '', '043')

-- 44 Grupo Completo Precio Fijo en Bono o Monedero
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(44, 'Grupo Completo Precio Fijo en Bono o Monedero', '&nbsp;&nbsp;Se declara en promoción a un grupo de artículos. Luego, a cada grupo <i>completo</i> de estos artículos que se encuentre  contenido en el ticket, se le aplica un descuento fijo. Dicho descuento fijo resulta de la diferencia entre el precio real del grupo de artículos y el precio  fijo (promocional) que haya sido configurado para esa promoción.<br/>&nbsp;&nbsp;El beneficio otorgado por la promoción se entrega en un <b><i>bono</i></b>  que contiene el monto de descuento calculado, o puede ser entregado como puntos en el <b><i>monedero</i></b> electrónico.', '', '044')

-- 46 Artículo por Cantidad Bonificacion en Bono o Monedero
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(46, 'Artículo por Cantidad Bonificacion en Bono o Monedero', '&nbsp;&nbsp;Se declara en promoción a un conjunto de artículos, y se le aplica un descuento <i>fijo</i> (configurable) a todos los  artículos de este conjunto que se encuentren contenidos en el ticket.<br/>&nbsp;&nbsp;El beneficio otorgado por la promoción se entrega en un  <b><i>bono</i></b> que contiene el monto de descuento calculado, o puede ser entregado como puntos en el <b><i>monedero</i></b> electrónico.', '', '046')

-- 47 Depto proveedor descuento BONO MONEDERO 
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(47, 'Depto Proveedor Descuento en Bono o Monedero', '&nbsp;&nbsp;Se declara en promoción a un conjunto de departamentos y a un conjunto de proveedores. Luego, se le aplica un descuento a  todos los artículos contenidos en el ticket, que pertenezcan a alguno de estos departamentos y, al mismo tiempo, pertenezcan a alguno de los proveedores  promocionados.<br/>&nbsp;&nbsp;El descuento aplicado puede ser de 2 tipos:<br/>(a) <b><i>Descuento porcentual</i></b>, en donde se calcula un porcentaje de  descuento sobre el precio de cada artículo beneficiado, o (b) <b><i>Descuento de monto fijo</i></b> por intervalo de dinero, en donde se descuenta una X  cantidad de dinero por cada Y unidades de dinero que sumen los artículos beneficiados.<br/>&nbsp;&nbsp;El beneficio otorgado por la promoción se entrega en  un <b><i>bono</i></b> que contiene el monto de descuento calculado, o puede ser entregado como puntos en el <b><i>monedero</i></b> electrónico.', '',  '047')

-- 48 Artículo por Cantidad Cupón Externo
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(48, 'Artículo por Cantidad Cupón Externo', '&nbsp;&nbsp;Se declara en promoción a un conjunto de artículos y a un cupón externo. Luego, la promoción habilitará como medio de pago  <i>un</i> cupón externo <i>por cada</i> artículo del conjunto que haya sido comprado, siempre y cuando el precio del artículo sea mayor o igual que el precio  del cupón.', '', '048')

-- 49 Artículo por Cantidad Agregar Artículo en Ticket
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(49, 'Artículo por Cantidad Agregar Artículo en Ticket', '&nbsp;&nbsp;Se declara un conjunto <b><i>D</i></b> de artículos disparantes de la promoción y un conjunto <b><i>B</i></b> de artículos  beneficiados por la promoción. Luego, por cada <b><i>m</i></b> artículos del conjunto <b><i>D</i></b> que hayan sido comprados, se aplicará un descuento  <i>porcentual</i> a <b><i>n</i></b> artículos del conjunto del tipo <b><i>B</i></b>, siempre que estos últimos hayan sido comprados al momento de aplicarse  la promoción.<br/>&nbsp;&nbsp;El descuento calculado por la promoción se aplica en el ticket.', '', '049')

-- 50 Departamento Proveedor Descuento en Ticket
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(50, 'Departamento Proveedor Descuento en Ticket', '&nbsp;&nbsp;Se declara en promoción a un conjunto <b><i>D</i></b> de departamentos y a un conjunto <b><i>P</i></b> de proveedores.  Luego, se aplica un descuento a todos los artículos contenidos en el ticket, que pertenezcan simultáneamente a ambos conjuntos. Esto es, se aplica un  descuento a todos los artículos que pertenezcan a alguno de los departamentos promocionados y, al mismo tiempo, pertenezcan a alguno de los proveedores  promocionados.<br/>&nbsp;&nbsp;El descuento aplicado puede ser de 2 tipos: (a) <b><i>Descuento porcentual</i></b>, en donde se calcula un porcentaje de  descuento sobre el precio de cada artículo beneficiado, o (b) <b><i>Descuento de monto fijo</i></b> por intervalo de dinero, en donde se descuenta una X  cantidad de dinero por cada Y unidades de dinero que sumen los artículos beneficiados.<br/>&nbsp;&nbsp;El cálculo del descuento puede ser realizado sobre el  importe original de los artículos, o sobre el valor resultante de haber aplicado sobre ellos otras promociones (<b><i>Aplica sobre beneficios  anteriores</i></b>).<br/>&nbsp;&nbsp;El descuento calculado por la promoción se aplica al ticket, sobre un artículo de descarga previamente configurado.',  '', '050')

-- 52 Pago con Tarjeta Descuento en Bono o Monedero y Mesaje en Cupón
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(52, 'Pago con Tarjeta Descuento en Bono o Monedero y Mesaje en Cupón', '&nbsp;&nbsp;Se declara en promoción a un conjunto de tarjetas y planes. Luego, se calcula un descuento sobre el importe de dinero que  haya sido pagado con esas tarjetas.<br/>&nbsp;&nbsp;El descuento aplicado puede ser de 2 tipos: (a) <b><i>Descuento porcentual</i></b>, en donde se calcula  un porcentaje de descuento sobre el precio de cada artículo beneficiado, o (b) <b><i>Descuento de monto fijo</i></b> por intervalo de dinero, en donde se  descuenta una X cantidad de dinero por cada Y unidades de dinero que sumen los artículos beneficiados.<br/>&nbsp;&nbsp;El beneficio otorgado por la promoción  se entrega en un <b><i>bono</i></b> que contiene el monto de descuento calculado, o puede ser entregado como puntos en el <b><i>monedero</i></b>  electrónico.<br/>&nbsp;&nbsp;Por otro lado, si se realizan pagos con otras tarjetas que no sean las promocionadas, la promoción imprimirá un cupón indicando  el monto de dinero que el cliente se ha perdido de ganar.', '', '052')

-- 53 Monto Premio Ruleta
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(53, 'Monto Premio Ruleta', '&nbsp;&nbsp;Se declara un conjunto de premios integrado por ciertos artículos más un descuento al total del ticket. Luego, si el monto total del ticket supera una cantidad establecida, la promoción elegirá al azar uno de estos premios y lo otorgará.&nbsp;&nbsp;Cabe aclarar que el sorteo de los premios se realiza con igual probabilidad para cada uno de ellos, es decir, si el conjunto de premios está integrado por 9 artículos más el descuento al ticket, cada premio tiene una probabilidad de 0,10 de ser otorgado.&nbsp;&nbsp;El beneficio calculado por la promoción se aplica al ticket. Si el premio otorgado es el descuento al total del ticket, el beneficio se entrega sobre un artículo de descarga previamente configurado.', '', '053')

-- 54 Perfil Descuento en Ticket
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(54, 'Perfil Descuento en Ticket', '&nbsp;&nbsp;Se declara en promoción un conjunto de perfiles y se le asigna a cada uno un descuento. Luego, si el perfil del cliente registrado en la compra coincide con alguno de los perfiles promocionados, se aplica el descuento correspondiente sobre el monto total del ticket.&nbsp;&nbsp;El beneficio de la promoción se aplica en el ticket sobre un artículo de descarga previamente configurado.', '', '054')

-- 56 Bolsón Agregar Artículo en Ticket
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(56, 'Bolsón Agregar Artículo en Ticket', '&nbsp;&nbsp;Se declara en promoción un conjunto <b><i>C</i></b> de artículos que se deben comprar, y un conjunto <b><i>B</i></b> de artículos beneficiados. Luego, si el cliente compra al menos un artículo del conjunto <b><i>C</i></b> y, además, compra un conjunto <b><i>B</i></b> completo, la promoción entregará alguno de los artículos del conjunto <b><i>B</i></b> a un precio promocional.&nbsp;&nbsp;El beneficio de la promoción se aplica en el ticket, descargando el descuento sobre el mismo artículo.', '', '056')

-- 57 Grupo Premio Ruleta
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(57, 'Grupo Premio Ruleta', '&nbsp;&nbsp;Se declara en promoción un conjunto <b><i>A</i></b> de artículos promocionados y un conjunto <b><i>P</i></b> de premios. Luego, si el cliente compra artículos del conjunto <b><i>A</i></b> superando una cantidad mínima preestablecida, la promoción elegirá al azar uno de los premios y lo otorgará como beneficio.&nbsp;&nbsp;El conjunto <b><i>P</i></b> de premios está integrado por ciertos artículos, más un descuento al total del ticket, más un descuento a los artículos del conjunto <b><i>A</i></b>.&nbsp;&nbsp;El beneficio calculado por la promoción se aplica al ticket. Si el premio otorgado es el descuento al total del ticket, el beneficio se entrega sobre un artículo de descarga previamente configurado, sino se aplica sobre el artículo que haya sido elegido.', '', '057')

-- 58 Artículo Bonificación Puntos Cliente Fiel
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(58, 'Artículo Bonificación Puntos Cliente Fiel', '&nbsp;&nbsp;Se declara en promoción a un conjunto de artículos con cantidades específicas. Luego, se otorgan <b><i>n</i></b> puntos por cada <b><i>m</i></b> unidades de dinero que sumen los artículos de este conjunto que hayan sido comprados.', '', '058')

-- 59 Importe Total Bonificación Puntos Cliente Fiel
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(59, 'Importe Total Bonificación Puntos Cliente Fiel', '&nbsp;&nbsp;Esta promoción otorga puntos sobre el monto total del ticket, excluyendo aquellos artículos declarados como no promocionables. Esta promoción permite configurar la cantidad de puntos que se desea regalar al cliente fiel, según el monto de la compra que el mismo realice.', '', '059')

-- 63 Clasificación Obliga Medios
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(63, 'Clasificación Obliga Medios', '', '', '063')

-- 75 Almacor_Artículo por Cantidad Agregar Artículo en Ticket
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [XFORM])
VALUES(75, 'Almacor_Artículo por Cantidad Agregar Artículo en Ticket', '&nbsp;&nbsp;Se declara un conjunto <b><i>D</i></b> de artículos disparantes de la promoción y un conjunto <b><i>B</i></b> de artículos  beneficiados por la promoción. Luego, por cada <b><i>m</i></b> artículos del conjunto <b><i>D</i></b> que hayan sido comprados, se aplicará un descuento  <i>porcentual</i> a <b><i>n</i></b> artículos del conjunto del tipo <b><i>B</i></b>, siempre que estos últimos hayan sido comprados al momento de aplicarse  la promoción.<br/>&nbsp;&nbsp;El descuento calculado por la promoción se aplica en el ticket.', '', '075')

-- 76 Almacor_Artículo por Cantidad Agregar Artículo en Ticket
INSERT INTO TYPE_PROMO ([TYPE_PROMO], [DESCRIPTION], [DOCUMENTATION], [DESCRIPTION_INVEL], [ES_IMPUESTO])
VALUES(76, 'Grupo Parcial Precio Fijo en Ticket', '&nbsp;&nbsp;Se declara en promoción a un grupo de artículos. Luego, a cada grupo <i>parcial</i> de estos  artículos que se encuentre contenido en el ticket, se le aplica un descuento fijo para obtener el precio del grupo. Dicho descuento fijo resulta de la diferencia entre el precio real del  grupo de artículos y el precio fijo (promocional) que haya sido configurado para esa promoción.<br/>&nbsp;&nbsp;El descuento calculado por la promoción se  aplica al ticket, distribuyéndolo proporcionalmente entre todos los artículos beneficiados.', '', 0);

